---
- name: Enrol
  hosts: all
  gather_facts: no
  become: no

  tasks:
    - name: Set authorized key for user ubuntu copying it from current user
      ansible.posix.authorized_key:
        user: ruser
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
